import bounds_solutions_equilibrium_problems_solid_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace bounds_solutions_equilibrium_problems_solid_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end bounds_solutions_equilibrium_problems_solid_theorem_canonical_lane_mathlib
end HautevilleHouse
